use vkorginizer_db;

insert into years (NameYear) values (2021);

insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'January', 1);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'February', 2);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'March', 3);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'April', 4);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'May', 5);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'June', 6);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'July', 7);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'August', 8);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'September', 9);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'October', 10);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'November', 11);
insert into Months(Year_Fk, NameMonth, NumberMonth) values (1, 'December', 12);

insert into Weeks(Month_Fk, NameWeek) values (1, 53);
insert into Weeks(Month_Fk, NameWeek) values (1, 1);

insert into Days(Week_Fk, DateDay) values (1, 1);
insert into Days(Week_Fk, DateDay) values (1, 2);
insert into Days(Week_Fk, DateDay) values (1, 3);
insert into Days(Week_Fk, DateDay) values (2, 4);
insert into Days(Week_Fk, DateDay) values (2, 5);
insert into Days(Week_Fk, DateDay) values (2, 6);
insert into Days(Week_Fk, DateDay) values (2, 7);
insert into Days(Week_Fk, DateDay) values (2, 8);
insert into Days(Week_Fk, DateDay) values (2, 9);
insert into Days(Week_Fk, DateDay) values (2, 10);

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (1, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (2, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');


insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (3, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (4, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (5, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (6, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (7, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (8, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (9, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');

insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '00:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №1');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '01:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №2');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '02:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №3');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '03:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №4');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '04:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №5');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '05:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №6');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '06:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №7');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '07:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №8');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '08:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №9');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '09:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №10');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '10:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №11');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '11:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №12');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '12:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №13');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '13:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №14');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '14:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №15');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '15:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №16');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '16:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №17');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '17:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №18');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '18:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №19');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '19:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №20');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '20:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №21');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '21:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №22');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '22:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №23');
insert into Tasks(Days_Fk, NameTask, TimeTask, DescriptionTask) values (10, 'Закончить органайзер php', '23:00:00', 'Тут необходимо указать важные нюансы для выполнения задачи №24');